# Generated by Django 2.0.10 on 2019-01-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
