# Generated by Django 2.0.10 on 2019-01-20 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190120_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='taglist',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
